FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Copy app source
COPY . .

# Expose port
EXPOSE 5000

# Start app
CMD ["node", "server.js"]